### ISSUE TITLE
Does not work with websockets >= 4.0

### ISSUE THREAD

**Issue by smmalis37** [Rapptz/discord.py#973]
Per https://github.com/aaugustin/websockets/commit/0827eeee5bfe8b776dfae70642a336d324435027 the force keyword is no longer supported in close_connection. This causes the following error when trying to call it currently:

TypeError: close_connection() got an unexpected keyword argument 'force'

**Comment by khazhyk** [comment]
From requirements.txt, this looks like a known issue;

```
websockets>=3.1,<4.0
```

**Comment by datmellow** [comment]
The dependances for discord.py are pinned. 
https://before-you-ship.18f.gov/infrastructure/pinning-dependencies/

And as such are not designed to work on other versions.

**Comment by dotlambda** [comment]
It would be really nice if you made it compatible with websockets>=4.0 though, because otherwise distros won't be able to package websockets and discord.py in a consistent way.

**Comment by ashkitten** [comment]
Agreed, I think this should be updated to work with the latest websockets
