### ISSUE TITLE
How do I fix my deletion script so that it works with 3.7? 

### ISSUE THREAD

**Issue by fwanky** [Rapptz/discord.py#1913]
Arch user, so yeah. I miss 3.6 but I don't think there's really anyway to have them both installed without everything breaking.

Here's my error when trying to run my script via 3.7

py3 del.py 
Logged in as user - userid
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/discord/client.py", line 227, in _run_event
    await coro(*args, **kwargs)
  File "del.py", line 22, in on_message
    async for m in c.logs_from(message.channel,limit=t):
AttributeError: 'Client' object has no attribute 'logs_from'

**Comment by Phxntxm** [comment]
It looks to me like you are using discord.py's rewrite version...not the async version. `logs_from` does not exist in rewrite, it's `channel.history`:

https://discordpy.readthedocs.io/en/rewrite/api.html#discord.abc.Messageable.history

**Comment by Harmon758** [comment]
See the [Migrating to v1.0](https://discordpy.readthedocs.io/en/rewrite/migrating.html#migrating-to-v1-0) section of the documentation, specifically, the [Models are Stateful](https://discordpy.readthedocs.io/en/rewrite/migrating.html#models-are-stateful) and [Asynchronous Iterators](https://discordpy.readthedocs.io/en/rewrite/migrating.html#asynchronous-iterators) subsections.

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
