### ISSUE TITLE
Import failed

### ISSUE THREAD

**Issue by lambor590** [Rapptz/discord.py#3993]
I'm trying to run a bot that I made, but when I run it, it shows me this:

Traceback (most recent call last):
  File "mybot.py", line 3, in <module>
    import discord
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\__init__.py", line 23, in <module>
    from .client import Client
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 35, in <module>
    import websockets
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\__init__.py", line 3, in <module>
    from .auth import *
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\auth.py", line 15, in <module>
    from .server import HTTPResponse, WebSocketServerProtocol
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\server.py", line 49, in <module>
    from .protocol import WebSocketCommonProtocol
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 18, in <module>
    from typing import (
ImportError: cannot import name 'Deque'

**Comment by TheRockettek** [comment]
Try not using 3.6.0, websockets does not like that version but will work on 3.6.1

**Comment by lambor590** [comment]
> Try not using 3.6.0, websockets does not like that version but will work on 3.6.1

Ok, I will try it

**Comment by lambor590** [comment]
In Python 3.6.1 works fine, thanks
